accounts/urls.py
from django.urls import path
from django.contrib.auth.views import login, logout
from . import views

urlpatterns = [
	path('login/', login, name='login', kwargs={
			'template_name': 'accounts/login_form.html',
			}),
	path('logout/', logout, name='logout', kwargs={'next_page': 'login',}),
	path('signup/', views.signup, name='signup'),
	path('profile/', views.profile, name='profile'),
	]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
	path('', views.index, name='index'),
    path('<pk>', views.post_detail, name='post_detail'),
	path('<post_pk>/comment/new/', views.comment_new, name='comment_new'),
	path('<post_pk>/comment/<pk>/edit/', views.comment_edit, name='comment_edit'),
	path('<post_pk>/comment/<pk>/delete/', views.comment_delete, name='comment_delete'),
]

photowall/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('blog/', include('blog.urls', namespace='blog')),
	path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
import re
from django.conf import settings
from django.urls import reverse
from django import forms
from django.db import models


def lnglat_validator(value):
    if not re.match(r'^[+-]?\d+\.?\d*,[+-]?\d+\.?\d*$', value):
        raise forms.ValidationError('경도/위도를 입력해주세요.')

class Post(models.Model):
	title = models.CharField(max_length=100)
	content = models.TextField()
	photo = models.ImageField()
	lnglat = models.CharField(max_length=40, blank=True, validators=[lnglat_validator])
	is_public = models.BooleanField(default=False)
	create_at = models.DateTimeField(auto_now_add=True)
	update_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title
	
	def get_absolute_url(self):
		return reverse('blog:post_detail', args=[self.pk])

	@property
	def lng(self):
		if self.lnglat:
		    return self.lnglat.split(',')[0]
		return None

	@property
	def lat(self):
		if self.lnglat:
		    return self.lnglat.split(',')[1]
		return None


class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	message = models.TextField()
	create_at = models.DateTimeField(auto_now_add=True)
	update_at = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ['-id']

	def get_edit_url(self):
		return reverse('blog:comment_edit', args=[self.post.pk, self.pk])

	def get_delete_url(self):
		return reverse('blog:comment_delete', args=[self.post.pk, self.pk])

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class SignupForm(UserCreationForm):
	class Meta(UserCreationForm.Meta):
		fields = UserCreationForm.Meta.fields + ('email',)

	def clean_email(self):
		email = self.cleaned_data.get('email', '')
		if email:
			if get_user_model().objects.filter(email=email).exists():
				raise forms.ValidationError('duplicated email')
		return email

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['message']

accounts/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from .forms import SignupForm


def signup(request):
	if request.method == 'POST':
		form = SignupForm(request.POST)
		if form.is_valid():
			user = form.save()
			return redirect(settings.LOGIN_URL)
	else:
		form = SignupForm()
	return render(request, 'accounts/signup_form.html', {
	'form': form,
	    })

def profile(request):
	return render(request, 'accounts/profile.html')

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Post, Comment
from .forms import CommentForm

def index(request):
	post_list = Post.objects.all()
	return render(request, 'blog/post_list.html', {
			'post_list': post_list,
			})

def post_detail(request, pk):
	post = get_object_or_404(Post, pk=pk)
	return render(request, 'blog/post_detail.html', {
			'post': post,
			})
@login_required
def comment_new(request, post_pk):
	post = get_object_or_404(Post, pk=post_pk)

	if request.method == 'POST':
		form = CommentForm(request.POST, request.FILES)
		if form.is_valid():
			comment = form.save(commit=False)
			comment.post = post
			comment.author = request.user
			comment.save()
			return redirect('blog:post_detail', post.pk)
	else:
		form = CommentForm()
	return render(request, 'blog/comment_form.html', {
		'form': form
	})

@login_required
def comment_edit(request, post_pk, pk):
	comment = get_object_or_404(Comment, pk=pk)
	if comment.author != request.user:
		return redirect(comment.post)

	if request.method == 'POST':
		form = CommentForm(request.POST, request.FILES, instance=comment)
		if form.is_valid():
			comment = form.save()
			return redirect(comment.post)
	else:
		form = CommentForm(instance=comment)
	return render(request, 'blog/comment_form.html', {
		'form': form
	})

@login_required
def comment_delete(request, post_pk, pk):
	comment = get_object_or_404(Comment, pk=pk)
	if comment.author != request.user:
	    return redirect(comment.post)

	if request.method == 'POST':
	    comment.delete()
	    return redirect(comment.post)

	return render(request, 'blog/comment_confirm_delete.html', {
			'comment': comment,
			})

accounts/templates/accounts/layout.html
{% extends "layout.html" %}

accounts/templates/accounts/login_form.html
{% extends "accounts/layout.html" %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
	<table>
	    {{ form.as_table }}
	</table>
	<input type="submit" />
</form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "accounts/layout.html" %}

{% block content %}
<h1>{{ user }}'s Profile</h1>

<table>
    <tr><th>username</th><td>{{ user.username }}</td></tr>
	<tr><th>email</th><td>{{ user.email }}</td></tr>
	<tr><th>date_joined</th><td>{{ user.date_joined }}</td></tr>
</table>
{% endblock %}

accounts/templates/accounts/signup_form.html
{% extends "accounts/layout.html" %}

{% block content %}
<form actino="" method="post">
    {% csrf_token %}
	<table>
	    {{ form.as_table }}
	</table>
	<input type="submit" />
</form>
{% endblock %}

blog/templates/blog/comment_confirm_delete.html
<form action="" method="post">
    {% csrf_token %}
	정말 삭제하시겠습니까?
	<input type="submit" value="삭제하겠습니다." />
</form>

blog/templates/blog/comment_form.html
<form action="" method='post'>
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block extra_head %}
<style>
    .post_photo {
		max-width: 100%;
	}
    .post-map {
		width: 300px;
		height: 300px;
	}
</style>

{% if post.lnglat %}
    <script>
    $(function() {
		var lat = {{ post.lat }};
		var lng = {{ post.lng }};
        var myLatLng = {lat: lat, lng: lng};
		var container = $('.post-map')[0];
        var map = new google.maps.Map(container, {
            zoom: 15,
			center: myLatLng
		});
		var marker = new google.maps.Marker({
			position: myLatLng,
			map: map,
			title: 'Hello World!'
		});
	});
    </script>
{% endif %}
    <script src="https://maps.googleapis.com/maps/api/js"></script>
{% endblock %}

{% block content %}
<div class="container">
    <div class="col-sm-12">
	    <div class="paner paner-default">
            <div class="panel-heading">
			    {{ post.title }}
			</div>
            <div class="panel-body">
	            {% if post.photo %}
				    <img src="{{ post.photo.url }}" class="post_photo" />
				{% endif %}
				<hr/>

				<div class="post-map"></div>

                {{ post.content|linebreaks }}

                <hr>
                {% for comment in post.comment_set.all %}
                <ul>
                    <li>
                        {{ comment.message }}
						by {{ comment.author }}
						at {{ comment.create_at }}
						{% if comment.author == request.user %}
                            <a href="{{ comment.get_edit_url }}">수정</a>
						    <a href="{{ comment.get_delete_url }}" class="text-danger">삭제</a>
						{% endif %}
                    </li>
                </ul>
                {% endfor %}
		    </div>
			<div class="panel-footer">
			    <a href="{% url "blog:index" %}" class="btn btn-default">목록으로</a>
                <a href="{% url "blog:comment_new" post.pk %}" class="btn btn-primary">댓글 쓰기</a>
			</div>
        </div>
	</div>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}
    <h1>PhotoWall</h1>

    <ul>
    {% for post in post_list %}
    <li>
	    <a href="{% url "blog:post_detail" post.pk %}">
        {{ post.title }}
		</a>
    </li>
    {% endfor %}
    </ul>
{% endblock %}

photowall/templates/layout.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
	<title>{% block title %}PhotoWall{% endblock %}</title>
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cosmo/bootstrap.min.css" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
{% block extra_head %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">PhotoWall</a>
			</div>
			<div id="navbar" class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li class="active"><a href="#">Home</a></li>
					<li><a href="#about">About</a></li>
					<li><a href="#contact">Contact</a></li>
				</ul>
				<ul class="nav navbar-nav pull-right">
				    {% if not user.is_authenticated %}
						<li><a href="{% url "login" %}?next={{ request.path }}">Login</a></li>
						<li><a href="{% url "signup" %}">Signup</a></li>
					{% else %}
						<li><a href="{% url "profile" %}">Profile</a></li>
						<li><a href="{% url "logout" %}?next={{ request.path }}">Logout</a></li>
					{% endif %}
				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</nav>
    <div class="container">
		<div class="row">
			<div class="col-sm-12">
				{% block content %}
				{% endblock %}
			</div>
		</div>
	</div>
</body>
</html>